name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # Build
      - name: Build with Maven
        run: mvn -B package --file pom.xml


      - name: Auto release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          files: |
            spigot/target/geyserutils-*.jar
            geyser/target/geyserutils-*.jar
            velocity/target/geyserutils-*.jar
            bungee/target/geyserutils-*.jar
